### ISSUE TITLE
Dag file editor can browse files, but cannot open it - file not found

### ISSUE THREAD

**Issue by mburso** [andreax79/airflow-code-editor#55]
After upgrading apache-airflow from 2.2.3 to 2.3.3, started getting error while trying to open files thru dag-code-editor 6.0.0.

I can navigate in all folders, see all files, but when trying to open any of them "file not found" issue shows up

![2022-08-11 11_04_36-Window](https://user-images.githubusercontent.com/78361374/184152043-44e93f97-d3a1-45a5-b6b3-d033131f1744.png)

![2022-08-11 11_04_44-Window](https://user-images.githubusercontent.com/78361374/184152072-6670130c-0a1b-4504-b040-d74b856a0dad.png)

Currrent folder config:
```
[core]
dags_folder = /data/airflow/dags

[code_editor]
 root_directory = /data/airflow
```

**Comment by andreax79** [comment]
Logs can be very useful, please check the browser console for any javascript error and the airflow logs.

**Comment by mburso** [comment]
Will do. 

Working after downgrade airflow-code-editor to 5.2.2

**Comment by camilaagw** [comment]
I had the exact same issue, and got the following error by looking at the logs:
```
[[34m2022-08-18 17:00:38,159[0m] {[34mcode_editor_view.py:[0m116} ERROR[0m - send_file() got an unexpected keyword argument 'attachment_filename'
```

**Comment by andreax79** [comment]
Which version have you installed?

**Comment by camilaagw** [comment]
I had version 7.0.0, but also version 6.0.0 gave me the same error.  Downgrading to 5.2.2 made the bug disappear.

**Comment by andreax79** [comment]
It's problem with the new version of Flask.
Fixed in version 7.0.1.
